"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
show_hidden = true

[opener]
edit = [{ exec = '${EDITOR:=vi} "$@"', desc = "$EDITOR", block = true, for = "linux" }]
open = [{ exec = '${EDITOR:=vi} "$@"', desc = "$EDITOR", block = true, for = "linux" }]

